spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agent_insight?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://127.0.0.1:19200}

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.agentinsight: debug
